### ISSUE TITLE
access to related objects is inefficient

### ISSUE THREAD

**Issue by mhl** [everypolitician/everypolitician-popolo-python#3]
For example, if you have a `Membership` object, and want to fetch the `Person` object it relates to, the `Membership.person` method is `O(n)` in the number of people in the Popolo JSON.

A simple solution to this is that each PopoloCollection subclass could store a dict that maps (for example) person IDs to the corresponding Person object. That would help with the related object properties of `Membership`.

The `Person.memberships` would need a different dict to be populated at import time (mapping person IDs to all Membership objects for those people).

This would be worth doing, I think, since otherwise straightforward-looking code may be unexpectedly very slow.

**Comment by chrismytton** [comment]
Related to https://github.com/everypolitician/everypolitician-popolo/pull/65 where we did something similar.
