### ISSUE TITLE
make it easier to get the latest term

### ISSUE THREAD

**Issue by mhl** [everypolitician/everypolitician-popolo-python#8]
At the moment if you want to find the latest legislative period in some Popolo data you have to do something like:

```python
latest_term = sorted(
    (e for e in popolo.events if e.classification == 'legislative period'),
    key=lambda e: e.start_date
)[-1]
```

It would be much nicer if you could do something like:

```python
latest_term = popolo.events.latest_legislative_period
```

To check out the equivalent code in the Ruby gem, you can start here: https://github.com/everypolitician/everypolitician-popolo/blob/9ae887ee204135f8da6b61ca9e26b6bd9b64241a/lib/everypolitician/popolo.rb#L55-L63

**Comment by andylolz** [comment]
Just to note here (though I’m sure you’re already aware): In the ruby version, `current_term` and `current_legislative_period` are both deprecated. See:
https://github.com/everypolitician/everypolitician-popolo/commit/09558040
